name: Ubuntu 16.04 SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Start 16.04 Container in Background
        run: |
          docker run -d --name xenial_64 --privileged \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ubuntu:16.04 tail -f /dev/null
      - name: Prepare Container Repositories
        run: |
          docker exec -i xenial_64 bash -c "cat << 'EOF' > /etc/apt/sources.list
          deb http://old-releases.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
          deb http://old-releases.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
          deb http://old-releases.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
          EOF"
          docker exec xenial_64 apt-get update
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        with:
          # Restricts SSH entry exclusively to your personal GitHub profile
          limit-access-to-actor: true 
