name: Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Prepare the environment
        run: |
          sudo apt update
          sudo apt-get install tmate
      - name: Running tmate
        run: |
          tmate -F & while true; do sleep 1; echo "TMATE"; done
