name: Ubuntu12 SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Start 32-bit Container in Background
        run: |
          docker run -d --name precise_32 --privileged --platform linux/386 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            i386/ubuntu:12.04 tail -f /dev/null
      - name: Prepare Container Repositories
        run: |
          docker exec precise_32 sed -i 's/://ubuntu.com' /etc/apt/sources.list
          docker exec precise_32 sed -i 's/://ubuntu.com' /etc/apt/sources.list
          docker exec precise_32 apt-get update
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
