name: Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Running tmate
        run: |
          bash path/script.sh
